server:
  servlet:
    context-path: /manage_store/v1
  port: 8080

spring:
  application:
    name: manage-store-showroom
  output:
    ansi:
      enabled: always
  datasource:
    url: ${MYSQL_URL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    url: ${MYSQL_URL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    locations: classpath:db/migration