server:
  servlet:
    context-path: /manage_store/v1
  port: 8080
  connection-timeout: 5s

spring:
  application:
    name: manage-store-showroom
  output:
    ansi:
      enabled: always
  datasource:
    url: ${MYSQLURL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

  flyway:
    enabled: true
    url: ${MYSQLURL}
    user: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    locations: classpath:db/migration
cors:
  allowedorigins: ${CORSALLONEORIGINS}


logging:
  level:
    br.com.manage.store: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


