CREATE TABLE tb_customer(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    cpf VARCHAR(14) UNIQUE,
    email VARCHAR(60) UNIQUE,
    phone VARCHAR(19),
    date_birth DATE,
    marital_status VARCHAR(20),
    enterprise VARCHAR(50),
    business_phone VARCHAR(19),
    length_service VARCHAR(20),
    business_zip_code VARCHAR(10),
    business_address VARCHAR(60),
    business_city VARCHAR(20),
    business_state VARCHAR(20),
    business_position VARCHAR(50),
    bank VARCHAR(20),
    agency VARCHAR(15),
    father VARCHAR(60),
    mother VARCHAR(60),
    zip_code VARCHAR(9),
    address VARCHAR(60),
    number VARCHAR(10),
    references_point VARCHAR(60),
    complement VARCHAR(20),
    city VARCHAR(20),
    state VARCHAR(20),
    create_at DATETIME
)